qlib_init:
    provider_uri: "~/.qlib/qlib_data/us_data"
    region: us
    exp_manager: 
        class: MLflowExpManager
        module_path: qlib.workflow.expm
        kwargs:
           uri: tra/mlruns
           default_exp_name: tra

market: &market all
benchmark: &benchmark SPY
filter_instruments: &filter_instruments ^(GLD|SHV|BWX|ASHR|FLOT|AAXJ|VGK|VWOB|LQD|PDBC|HYG|VNQ|QQQ|UUP|RSX|BNDX|VT|EEM|IEF|EWS|EWA|EWZ|EWJ|SPY|VIX)$
filter_start_time: &filter_start_time 2008-01-01
filter_end_time: &filter_end_time 2022-08-31
fit_start_time: &fit_start_time 2008-01-01
fit_end_time: &fit_end_time 2015-12-31
val_start_time: &val_start_time 2016-01-01
val_end_time: &val_end_time 2019-12-31
test_start_time: &test_start_time 2021-01-01
test_end_time: &test_end_time 2022-08-31

data_handler_config: &data_handler_config
    start_time: *filter_start_time
    end_time: *filter_end_time
    fit_start_time: *fit_start_time
    fit_end_time: *fit_end_time
    instruments: *market
    infer_processors:
      - class: RobustZScoreNorm
        kwargs:
          fields_group: feature
          clip_outlier: true
      - class: Fillna
        kwargs:
          fields_group: feature
    learn_processors:
      - class: CSRankNorm
        kwargs:
          fields_group: label
      label: ["Ref($close, -2) / Ref($close, -1) - 1"]
    filter_pipe:
      - filter_type: NameDFilter
        name_rule_re: *filter_instruments
        filter_start_time: *filter_start_time
        filter_end_time: *filter_end_time

tra_config: &tra_config
  num_states: *num_states
  rnn_arch: LSTM
  hidden_size: 32
  num_layers: 1
  dropout: 0.0
  tau: 1.0
  src_info: LR_TPE

model_config: &model_config
  input_size: 158
  hidden_size: 256
  num_layers: 2
  rnn_arch: LSTM
  use_attn: True
  dropout: 0.2

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 20
            n_drop: 5
    backtest:
        start_time: *test_start_time
        end_time: *test_end_time
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5

task:
  model:
    class: TRAModel
    module_path: qlib.contrib.model.pytorch_tra
    kwargs:
      tra_config: *tra_config
      model_config: *model_config
      model_type: RNN
      lr: 1e-3
      n_epochs: 100
      max_steps_per_epoch:
      early_stop: 20
      logdir: output/Alpha158_full
      seed: 0
      lamb: 1.0
      rho: 0.99
      alpha: 0.5
      transport_method: router
      memory_mode: *memory_mode
      eval_train: False
      eval_test: True
      pretrain: True
      init_state:
      freeze_model: False
      freeze_predictors: False
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *data_handler_config
     segments:
        train: [*fit_start_time, *fit_end_time]
        valid: [*val_start_time, *val_end_time]
        test: [*test_start_time, *test_end_time]
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs: 
        model: <MODEL>
        dataset: <DATASET>
    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs: 
        ana_long_short: False
        ann_scaler: 252
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config
